import { Food } from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Brilliant Bolognese',
    description: 'Vegan Bolognese with lentil-aubergine ragù.',
    cookTime: '10-20',
    price: 10.99,
    favourite: true,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: ['assets/food-1.webp', 'assets/ingredients-1.webp'],
    tags: ['Pasta', 'Protein'],
    isHovered: false,
  },
  {
    id: '2',
    name: 'Garden Gnocchi',
    description: 'Gnocchi with garden veggies & herb pesto.',
    price: 8.99,
    cookTime: '20-30',
    favourite: false,
    origins: ['Germany', 'UK'],
    stars: 4.7,
    imageUrl: ['assets/food-2.webp', 'assets/ingredients-2.webp'],
    tags: ['Potatoe', 'Vegan'],
    isHovered: false,
  },
  {
    id: '3',
    name: 'Peas & Love',
    description: 'Creamy pea-basil pasta, romanesco & tomatoes.',
    price: 7.99,
    cookTime: '10-15',
    favourite: false,
    origins: ['Germany', 'USA'],
    stars: 3.5,
    imageUrl: ['assets/food-3.webp', 'assets/ingredients-3.webp'],
    tags: ['Pasta', 'Protein'],
    isHovered: false,
  },
  {
    id: '4',
    name: 'Golden Curry',
    description: 'Creammy chikpea curry with pumpkin & spinach.',
    price: 7.99,
    cookTime: '15-20',
    favourite: true,
    origins: ['Belgium', 'France'],
    stars: 3.3,
    imageUrl: ['assets/food-4.webp', 'assets/ingredients-4.webp'],
    tags: ['Curry', 'Protein'],
    isHovered: false,
  },
  {
    id: '5',
    name: 'Karma Korma',
    description: 'Chikpea-curry with string beans & cauliflower.',
    price: 11.99,
    cookTime: '40-50',
    favourite: false,
    origins: ['India', 'Asia'],
    stars: 3.0,
    imageUrl: ['assets/food-5.webp', 'assets/ingredients-5.webp'],
    tags: ['Curry', 'Protein'],
    isHovered: false,
  },
  {
    id: '6',
    name: 'Mustard Veggie Roast',
    description: 'Sweet-sour mustard-glazed oven veggie mix.',
    price: 10.99,
    cookTime: '40-50',
    favourite: false,
    origins: ['Canada', 'USA'],
    stars: 4.0,
    imageUrl: ['assets/food-6.webp', 'assets/ingredients-6.webp'],
    tags: ['Potatoe', 'Vegan'],
    isHovered: false,
  },
  {
    id: '7',
    name: 'Naked Taco',
    description: 'Tex-Mex rice-bean mix with tomatoes & corn.',
    price: 7.99,
    cookTime: '40-50',
    favourite: true,
    origins: ['Mexico', 'Colombia'],
    stars: 4.0,
    imageUrl: ['assets/food-7.webp', 'assets/ingredients-7.webp'],
    tags: ['Protein', 'Rice', 'Vegan'],
    isHovered: false,
  },
  {
    id: '8',
    name: 'Glow Up',
    description: 'Sweet potatoe curry with carrots, parsnip & mango.',
    price: 7.99,
    cookTime: '40-50',
    favourite: false,
    origins: ['Vietnam', 'Asia'],
    stars: 4.0,
    imageUrl: ['assets/food-8.webp', 'assets/ingredients-8.webp'],
    tags: ['Curry', 'Potatoe', 'Vegan'],
    isHovered: false,
  },
  {
    id: '9',
    name: 'Pomodoro Passion',
    description: 'Mediterranean pasta with aubergine, carrots & beans.',
    price: 8.99,
    cookTime: '40-50',
    favourite: true,
    origins: ['Greece'],
    stars: 4.0,
    imageUrl: ['assets/food-9.png', 'assets/ingredients-9.webp'],
    tags: ['Protein', 'Pasta'],
    isHovered: false,
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 9 },
  { name: 'Protein', count: 6 },
  { name: 'Vegan', count: 4 },
  { name: 'Pasta', count: 3 },
  { name: 'Potatoe', count: 3 },
  { name: 'Curry', count: 3 },
  { name: 'Rice', count: 1 },
];
