import { Food } from "./app/shared/models/Food";
import { Tag } from "./app/shared/models/Tag";

export const sample_foods: Food[] = [
  {
    id: "1",
    name: "Brilliant Bolognese",
    description_short: "Vegan Bolognese with lentil-aubergine ragù.",
    description_long:"A vegan version of the ultimate crowd pleaser. An earthy, hearty mixture of eggplant, parsnips, carrots and lentils paired with al-dente linguine. Outstanding flavour that will transport you straight to Nonna’s kitchen.",
    cookTime: "10-20",
    price: 10.99,
    amount: 650,
    favourite: true,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: [
      "assets/food-1.webp",
      "assets/ingredients-1.webp",
      "assets/food-1-carousel-1.webp",
      "assets/food-1-carousel-2.webp",
    ],
    tags: ["Pasta", "Protein"],
    isHovered: false,
  },
  {
    id: "2",
    name: "Garden Gnocchi",
    description_short: "Gnocchi with garden veggies & herb pesto.",
    description_long:"An uplifting dish, full of vibrant Mediterranean garden veggies: string beans, spinach and tomato, accompanied by soft and fluffy gnocchi. All mixed in a sumptuous herb-bell pepper pesto, with a touch of crispy pumpkin seeds.",
    price: 8.99,
    amount: 570,
    cookTime: "20-30",
    favourite: false,
    origins: ["Germany", "UK"],
    stars: 4.7,
    imageUrl: [
      "assets/food-2.webp",
      "assets/ingredients-2.webp",
      "assets/food-2-carousel-1.webp",
      "assets/food-2-carousel-2.webp",
    ],
    tags: ["Potatoe", "Vegan"],
    isHovered: false,
  },
  {
    id: "3",
    name: "Peas & Love",
    description_short: "Creamy pea-basil pasta, romanesco & tomatoes.",
    description_long:"An ode to pesto, with a twist: blended green peas create an indulgent creaminess, complemented by flavorful basil. Paired with romanesco, broccoli and semi-dried tomatoes. Flavored with a sprinkle of pumpkin seeds and a dash of lemon juice.",
    price: 7.99,
    amount: 450,
    cookTime: "10-15",
    favourite: false,
    origins: ["Germany", "USA"],
    stars: 3.5,
    imageUrl: [
      "assets/food-3.webp",
      "assets/ingredients-3.webp",
      "assets/food-3-carousel-1.webp",
      "assets/food-3-carousel-2.webp",
    ],
    tags: ["Pasta", "Protein"],
    isHovered: false,
  },
  {
    id: "4",
    name: "Golden Curry",
    description_short: "Creammy chikpea curry with pumpkin & spinach.",
    description_long:"This ultimate comfort food bowl offers comfort minus the guilt. Indulge in a concoction of pumpkin, chickpeas, spinach and coconut milk. Infused with blends of garlic, ginger and turmeric to create a bowl of wholesome goodness.",
    price: 7.99,
    amount: 450,
    cookTime: "15-20",
    favourite: true,
    origins: ["Belgium", "France"],
    stars: 3.3,
    imageUrl: [
      "assets/food-4.webp",
      "assets/ingredients-4.webp",
      "assets/food-4-carousel-1.webp",
      "assets/food-4-carousel-2.webp",
    ],
    tags: ["Curry", "Protein"],
    isHovered: false,
  },
  {
    id: "5",
    name: "Karma Korma",
    description_short: "Chikpea-curry with string beans & cauliflower.",
    description_long:"A creamy curry with a blend of textures. A medley of sweet potato, chickpeas and wild rice. Paired with crisp cauliflower, string beans and sweet tomatoes. Blanketed in a creamy coconut sauce infused with turmeric and cardamom.",
    price: 11.99,
    amount: 750,
    cookTime: "40-50",
    favourite: false,
    origins: ["India", "Asia"],
    stars: 3.0,
    imageUrl: [
      "assets/food-5.webp",
      "assets/ingredients-5.webp",
      "assets/food-5-carousel-1.webp",
      "assets/food-5-carousel-2.webp",
    ],
    tags: ["Curry", "Protein"],
    isHovered: false,
  },
  {
    id: "6",
    name: "Mustard Veggie Roast",
    description_short: "Sweet-sour mustard-glazed oven veggie mix.",
    description_long:"A vibrant and crispy mix of veggies. Purple carrots, brussels sprouts and string beans, glazed with a delicately sweet mustard dressing. Infused with a fragrant touch of rosemary. A very cosy dish, perfect to share or enjoy solo.",
    price: 10.99,
    amount: 650,
    cookTime: "40-50",
    favourite: false,
    origins: ["Canada", "USA"],
    stars: 4.0,
    imageUrl: [
      "assets/food-6.webp",
      "assets/ingredients-6.webp",
      "assets/food-6-carousel-1.webp",
      "assets/food-6-carousel-2.webp",
    ],
    tags: ["Potatoe", "Vegan"],
    isHovered: false,
  },
  {
    id: "7",
    name: "Naked Taco",
    description_short: "Tex-Mex rice-bean mix with tomatoes & corn.",
    description_long:"You won’t miss the taco with this delicious bowl. A hearty mixture of a variety of rice, and beans, paired with sweet corn, onions and tomatoes. Rounded off with a spice blend of cumin, chili, paprika, cardamom and oregano.",
    price: 7.99,
    amount: 450,
    cookTime: "40-50",
    favourite: true,
    origins: ["Mexico", "Colombia"],
    stars: 4.0,
    imageUrl: [
      "assets/food-7.webp",
      "assets/ingredients-7.webp",
      "assets/food-7-carousel-1.webp",
      "assets/food-7-carousel-2.webp",
    ],
    tags: ["Protein", "Rice", "Vegan"],
    isHovered: false,
  },
  {
    id: "8",
    name: "Glow Up",
    description_short: "Sweet potatoe curry with carrots, parsnip & mango.",
    description_long:"Get ready for your glow up! Invigorating curry sensations on a bed of wild rice will excite your taste buds. Paired with parsnips, carrots, sweet potato and a delightful mango surprise. Rounded off with a blend of fresh lemongrass, turmeric, paprika and potato for a radiating health boost.",
    price: 7.99,
    amount: 450,
    cookTime: "40-50",
    favourite: false,
    origins: ["Vietnam", "Asia"],
    stars: 4.0,
    imageUrl: [
      "assets/food-8.webp",
      "assets/ingredients-8.webp",
      "assets/food-8-carousel-1.webp",
      "assets/food-8-carousel-2.webp",
    ],
    tags: ["Curry", "Potatoe", "Vegan"],
    isHovered: false,
  },
  {
    id: "9",
    name: "Pomodoro Passion",
    description_short: "Mediterranean pasta with aubergine, carrots & beans.",
    description_long:"An indulgent pasta bowl bursting with Mediterranean flavours that takes you straight to Nonna’s kitchen. A veggie mix of carrots, aubergine, spinach, celery and kidney beans, paired with al-dente pasta shells for some extra heartiness.",
    price: 8.99,
    amount: 570,
    cookTime: "40-50",
    favourite: true,
    origins: ["Greece"],
    stars: 4.0,
    imageUrl: [
      "assets/food-9.png",
      "assets/ingredients-9.webp",
      "assets/food-9-carousel-1.webp",
      "assets/food-9-carousel-2.webp",
    ],
    tags: ["Protein", "Pasta"],
    isHovered: false,
  },
];

export const sample_tags: Tag[] = [
  { name: "All", count: 9 },
  { name: "Protein", count: 6 },
  { name: "Vegan", count: 4 },
  { name: "Pasta", count: 3 },
  { name: "Potatoe", count: 3 },
  { name: "Curry", count: 3 },
  { name: "Rice", count: 1 },
];
